### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by pedrualves** [edwi-feitoza/bravia_proxy_api#4]
# pequenas sugestões

- [ ] encapsular o server.js no diretório dos fontes .js e não deixar na raiz do projeto
- [ ] o metodo responsável pelo response esta no controller
- [ ] cada resposta "{ status: 'ok' }" poderia ser suprida pelo aproveitamento de status code 200, 204, 201, 500, etc
- [ ] seria legal especificar a versão correta para uso do nodejs dentro do package.json
- [ ] se não me engano a convenção sugere lowercase para nome de collections
- [ ] o uso de ";" é opcional a partir do es6
- [ ] variaveis de ambiente podem ajudar no conceito de logs
- [ ] nodemon como devDependencies, colocaria como opcional e habilitaria outros scripts de inicialização
- [ ] helmet, compression e outras libs são rápidas de serem implementadas e trazem melhorias significantes pro projeto
- [ ] docker?

### novamente são apenas sugestões que eu aplicaria em meu projeto

**Comment by pedrualves** [comment]
@edwi-feitoza

**Comment by edwi-feitoza** [comment]
Ajustes realizados conforme sugestão!

Em breve implementarei motor de logs.
